# Generated by Django 2.0.3 on 2018-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
