# Generated by Django 2.0.3 on 2018-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20180424_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.TextField(choices=[('Mr', 'Monsieur'), ('Mlle', 'Mademoiselle'), ('Dr', 'Docteur')], default='Mr', max_length=200),
        ),
    ]
