# Generated by Django 2.0.3 on 2018-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(choices=[('Monsieur', 'Monsieur'), ('Mlle', 'Mademoiselle'), ('Dr', 'Docteur')], default='Monsieur', max_length=200),
        ),
    ]
