# Generated by Django 2.0.3 on 2018-04-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20180424_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
