# Generated by Django 2.0.3 on 2018-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20180424_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='street2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
