# Generated by Django 2.0.3 on 2018-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.IntegerField(blank=True, choices=[((221,), 'Tunisie'), ((75,), 'France'), (233, 'USA')], default=0, max_length=200),
        ),
    ]
