# Generated by Django 2.0.3 on 2018-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_auto_20180504_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[((221,), 'Tunisie'), ((75,), 'France'), (233, 'USA')], default=(75,), max_length=200),
        ),
    ]
