# Generated by Django 2.0.3 on 2018-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_auto_20180504_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[(221, 'Tunisie'), (75, 'France'), (233, 'USA')], default=75, max_length=200),
        ),
    ]
